// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetGames():Promise<main.Games>;

export function GetScreenshots():Promise<main.ScreenshotsDirs>;

export function GetScreenshotsForGame(arg1:string):Promise<main.ScreenshotsDir>;

export function GetSteamLibraryMeta():Promise<main.SteamLibraryMeta>;

export function OnWindowResize():Promise<void>;
