// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetGameInfo(arg1) {
  return window['go']['main']['App']['GetGameInfo'](arg1);
}

export function GetGames() {
  return window['go']['main']['App']['GetGames']();
}

export function GetLibraryInfo() {
  return window['go']['main']['App']['GetLibraryInfo']();
}

export function GetScreenshots() {
  return window['go']['main']['App']['GetScreenshots']();
}

export function GetScreenshotsForGame(arg1) {
  return window['go']['main']['App']['GetScreenshotsForGame'](arg1);
}

export function NativeOpen(arg1) {
  return window['go']['main']['App']['NativeOpen'](arg1);
}

export function OnWindowResize() {
  return window['go']['main']['App']['OnWindowResize']();
}
