// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetGames():Promise<main.GamesResponse>;

export function GetLibraryInfo():Promise<main.LibraryInfo>;

export function GetScreenshots():Promise<main.ScreenshotCollectionResponse>;

export function GetScreenshotsForGame(arg1:string):Promise<main.ScreenshotCollectionResponse>;

export function NativeOpen(arg1:string):Promise<void>;

export function OnWindowResize():Promise<void>;
