// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetGames() {
  return window['go']['main']['App']['GetGames']();
}

export function GetScreenshots() {
  return window['go']['main']['App']['GetScreenshots']();
}

export function GetSteamLibraryMeta() {
  return window['go']['main']['App']['GetSteamLibraryMeta']();
}

export function OnWindowResize() {
  return window['go']['main']['App']['OnWindowResize']();
}
